logging:
    level:
        org:
            springframework:
            security: DEBUG

server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080

spring:
    datasource:
        driver-class-name: ${DRIVER_CLASS_NAME}
        url: ${JDBC_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    sql:
        init:
            mode: never
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 200
                dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        display-request-duration: true
        disable-swagger-default-url: true

jwt:
    header: ${JWT_HEADER}
    secret: ${JWT_SECRET}
    token-validity-in-seconds: 86400

cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS_KEY}
            secretKey: ${AWS_SECRET_KEY}
        region:
            static: ap-northeast-2
        stack:
            auto: false
        s3:
            bucket: moreview