jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create secrets.properties
        run: |
          echo "${{ secrets.SECRET }}" > src/main/resources/secrets.properties

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          gradle-version: '8.7'

      - name: Build with Gradle
        run: |
          ./gradlew build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Create key.pem
        run: |
          echo "${{ secrets.SSH_KEY }}" > ./key.pem

      - name: Setup SSH Key
        run: |
          chmod 600 ./key.pem

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Send files via SCP
        run: |
          ls -al
          scp -i "./key.pem" -r build/libs/* woojin020605@${{ secrets.HOST }}:/home/woojin020605

      - name: Checkout again
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/woojin020605
            pwd
            sh deploy-ssh.sh
